version: '3'
services:
  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - my-network

  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    networks:
      - my-network
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - my-network
  # mongo:
  #   image: mongo
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #   ports:
  #     - '27017:27017'
  #   networks:
  #     - my-network
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
  #   environment:
  #     - discovery.type=single-node
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - "ELASTIC_PASSWORD=changeme"
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   networks:
  #     - my-network

networks:
  my-network:
