application:
  url:
    backend: http://localhost:3000
    frontend: http://localhost:4200
    cors: http://localhost:4200,http://localhost
databases:
  postgres:
    database: postgres
    user: postgres
    password: pass123
    host: postgres-service
    port: 5432
  redis:  
    url: redis://default:password@redis-service:6379/0
  mongo:  
    url: redis://default:password@localhost:6379/0
  elastic:  
    url: redis://default:password@localhost:6379/0
idp:
  facebook:
    appId: 1590269461471529
    secret: 9d1e3ae8795a602e56f1d4de5ff33b5b
    callbackurl: http://localhost:3000/v1/auth/facebook/callback