application:
  url:
    backend: http://localhost:3000
    frontend: http://localhost:4200
databases:
  postgres:
    database: postgres
    user: postgres
    password: pass123
    host: localhost
    port: 5432
  redis:  
    url: redis://default:password@localhost:6379/0
  mongo:  
    url: mongodb://root:password@mongo:27017/0
  elk:
    node: http://localhost:9200
    auth:
      username: elastic
      password: changeme